version: '3.8'

services:
  app:
    image: ${IMAGE_TAG}
    container_name: wecom-prod
    build: .
    env_file:
      - ./configs/prod.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    container_name: wecom-redis-prod
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data: