version: '3.8'

services:
  web:
    image: ${IMAGE_TAG}
    container_name: wecom-staging
    ports:
      - "8000:8000"
    env_file:
      - ./src/config/.env
    depends_on:
      - redis

  redis:
    image: redis:6.2-alpine
    container_name: wecom-redis-staging
    ports:
      - "6379:6379"